### ISSUE TITLE
Process guideline

### ISSUE THREAD

**Issue by Jood80** [GSG-K3/ca-application-website#1]

**Comment by karmelyoei** [comment]
### Time Guidelines

**You should estimate the time of each issue, try to make it limited with the common standards as a following** 

- T[1]d : 1 day

- T[2]d: 2 day

- T[4]: 4day

- T[1]h: 1 hour

- T[2]h: 2 hours

- T[4]h: 4 hours

**When completing issues please leave a comment with the time actually taken to complete the issue.**

**Comment by karmelyoei** [comment]
**Pull Requests Checklist** 

- [ ] Branch is up to date with master

 

- [ ] The project runs

- [ ]  You can download and install locally, and run the project locally

 

- [ ] All existing and new features run without bugs

- [ ]  The build script runs without error

 

- [ ] (If the project is already deployed to Heroku) the branch to be merged can deploy successfully to Heroku

 

- [ ] Code is consistent

- [ ]  Linter is used, no error messages

 

- [ ] Code is consistent with an agreed team style

 

- [ ] The naming of files is consistent with the project (e.g. all files named with camelCase)

 

- [ ] All tests should pass locally and on Travis

- [ ]  No console logs (Console.log is only used for crucial system messages (e.g. which port server is on)).
 

- [ ] Any console. logs used for debugging have been removed.

 

- [ ] Console.error is used in error handling.

- [ ]  global.console.log and global.console.error are mocked in tests when needed to   avoid littering the console

**Comment by karmelyoei** [comment]
### Merging Pull Requests

The one who opens the pull request is responsible for merging it after the approval has been submitted by the team leader and the other colleagues, **don't merge any pull requests while there are other pull requests before you, if you make a mistake with any of  pull requests delete them no need to stay inside the pull request list, And before that make sure to pull the origin master to solve the conflict locally**

**Comment by karmelyoei** [comment]
### Components

All components should always be defined as a directory, The main component file should be index.js, stylesheet style.css

- The component name should follow PascalCase style
```
LandingPage/
├── index.js
└── style.css
```
### Naming Branches
follow this style
```
common-component/Cards
```

### Commits
Every important commit should include the issue number
Write descriptive commit to show what you did
