### ISSUE TITLE
I have this problem [1] Proxy error: Could not proxy request /api/user/:userId/profile from localhost:3000 to http://localhost:4000.

### ISSUE THREAD

**Issue by karmelyoei** [GSG-K3/ca-application-website#109]
Any suggestion when I wanted to get the data from the backend to frontend I struggled with this problem

**Comment by RandInaim** [comment]
most of the time it means that there is another process running on that port try 
killall node -9

**Comment by Jood80** [comment]
yup, I usually face such problem and `killall node -9` solve it most of time. Although, some times an error in the sever may cause it
