### ISSUE TITLE
Cannot read property 'prototype' of undefined

### ISSUE THREAD

**Issue by karmelyoei** [GSG-K3/ca-application-website#127]
![Screenshot from 2020-06-15 20-55-44](https://user-images.githubusercontent.com/39573452/84690208-c70a4080-af4a-11ea-922d-4bba10629aff.png)

**Comment by karmelyoei** [comment]
I was working and everything was normal, till I get this error

**Comment by Jood80** [comment]
@karmelyoei  check this link https://github.com/expressjs/express/issues/3659

**Comment by karmelyoei** [comment]
YEAH, thank you, I noticed that I send a request to the backend with sending undefined property I fixed it thnx
