### ISSUE TITLE
Refreshing the Page

### ISSUE THREAD

**Issue by karmelyoei** [GSG-K3/ca-application-website#136]
is this a bug?
No 
 I have a question!

if the user refreshes the page after he/she uploads the required information, The button back to normal, how can I fix this
![Screenshot from 2020-06-17 15-54-49](https://user-images.githubusercontent.com/39573452/84902115-0eacdb80-b0b5-11ea-9804-82522004304d.png)
![Screenshot from 2020-06-17 15-55-13](https://user-images.githubusercontent.com/39573452/84902120-110f3580-b0b5-11ea-8dea-2cb6bfa75830.png)

**Comment by karmelyoei** [comment]
PR #122

**Comment by DuaaH** [comment]
you can use local storage to save  the submitted state then check it

**Comment by karmelyoei** [comment]
Oh right I totally forget about local storage Could you please show me how?

**Comment by DuaaH** [comment]
after updating the state for submitted you can save the submitted state in the local storage.
and in the didmount function check if it exists or not.

https://www.robinwieruch.de/local-storage-react
