### ISSUE TITLE
Database Schema

### ISSUE THREAD

**Issue by Jood80** [GSG-K3/ca-application-website#33]

**Comment by karmelyoei** [comment]
![GSGDatabase](https://user-images.githubusercontent.com/39573452/80009500-d2ecff80-84d1-11ea-9597-b7b85a0e6dfc.jpg)

**Comment by karmelyoei** [comment]
Updated the database schema with a picture column at the mentors and the stories tables :wink: --

![GSGDatabase](https://user-images.githubusercontent.com/39573452/80102180-164f7880-857b-11ea-8e73-35a115d2dda4.jpg)
