### ISSUE TITLE
Home screen/ Success stories 

### ISSUE THREAD

**Issue by Jood80** [GSG-K3/ca-application-website#46]
#6  
## Acceptance Criteria:
- [x] a Header of the related section
- [x] a description of this person story
- [x] his/ her name
- [x] his/ her job title
- [ ] an arrows to moving through the stories
---
- [x] **Route** :
  -  [x] Front-end: ` /home`
  -  [x] Back-end: `/api/home/success-stories `

- [x] Figma
![image](https://user-images.githubusercontent.com/56412800/80372495-46a95680-889c-11ea-9a31-de90a98d4ddb.png)

**Comment by RandInaim** [comment]
where is the api route as you need to bring the data from the DB
