### ISSUE TITLE
setting up the database 

### ISSUE THREAD

**Issue by karmelyoei** [GSG-K3/ca-application-website#60]
setting up the  database folders :point_down:

- [X]  database folder name
- [x]  sql folder 
- [x]   db_build.sql
 - [x]  fake_data.sql
- [x]   connection.js
- [x]   db_build.js
- [x]  fake_data.js

**Comment by karmelyoei** [comment]
For creating the database locally, we run these commands :

1. psql

1.  CREATE DATABASE (name of database);

1. CREATE USER (name of the user) WITH SUPERUSER PASSWORD '(put password)';

1. GRANT ALL PRIVILEGES ON DATABASE <database name here> TO <desired username entered previously>;

1.  DATABASE_URL= postgres://(username):(password)@localhost:5432/(database name)

1. added the DATABASE_URL inside the .env file

**Comment by karmelyoei** [comment]
I had an error when I run this command node db_build.js to create the database 
```js
Error: self signed certificate
    at TLSSocket.onConnectSecure (_tls_wrap.js:1492:34)
    at TLSSocket.emit (events.js:315:20)
    at TLSSocket._finishInit (_tls_wrap.js:935:8)
    at TLSWrap.ssl.onhandshakedone (_tls_wrap.js:693:12) {
  code: 'DEPTH_ZERO_SELF_SIGNED_CERT'
````

**Comment by karmelyoei** [comment]
I solved the problem by downloading the version of the pg by running this command
```js
npm i pg@7.4.3
````

**Comment by Jood80** [comment]
@karmelyoei  shouldn't you mention the ENUM type?
