### ISSUE TITLE
Daily stand-up meeting

### ISSUE THREAD

**Issue by RandInaim** [GSG-K3/ca-application-website#64]
###  Here will be the updates and notes of our stand-up meetings.

**Comment by Jood80** [comment]
working on Back end of success stories.
Note: to ensure that your server works properly check its path at package.json
I've changed mine to : ` "server": "cd server && nodemon src/index.js",
`

**Comment by karmelyoei** [comment]
29/4/2020 Today Woking on getting the data from the database and sending it to frontend client for the support section

Working on the footer section as well

**Comment by karmelyoei** [comment]
Worked on the navbar made a huge edits
I am working now on the footer section
