### ISSUE TITLE
Connecting server with the client 

### ISSUE THREAD

**Issue by karmelyoei** [GSG-K3/ca-application-website#65]

**Comment by karmelyoei** [comment]
Connecting the backend with the frontend
Please follow these steps:

1.  install the concurrently ,react-router-dom , and the axios to use them in our code
```js
Npm i concurrently
npm i react-router-dom
npm i axios 
```

**Comment by karmelyoei** [comment]
2. Build the route endpoints for the front-end react like this code

```js
import React, { Fragment } from 'react';
import {
	BrowserRouter as Router,
	Route,
	Switch,
	Redirect,
} from 'react-router-dom';
import Home from './Screens/Home';
import NotFoundPage from './Screens/NotFoundPage';

	return (
    <Fragment>
     <Router>
    <Switch>
    <Route path="/" exact component={Home} />
    <Route component={NotFoundPage} />
    <Redirect to="/404" />
      </Switch>
   </Router>
         </Fragment>

```

**Comment by karmelyoei** [comment]
3. in the server packagejson write these commands to run the server port and the client port at the same time
```js
"scripts": {
		"test": "echo \"Error: no test specified\" && exit 1"			"test": "echo \"Error: no test specified\" && exit 1",
		"build:client": "cd client && npm run build",
		"server": "nodemon server/index.js ",
		"client": "cd client && npm start",
		"dev": "concurrently \"npm run server\" \"npm run client\""
```

**Comment by karmelyoei** [comment]
4. Added this command in the client pakagejson file

```js
"proxy": "http://localhost:4000" 
```

**Comment by karmelyoei** [comment]
5. Run this command in the terminal to build the react and create a file called build inside your project 

```js
npm run build
```

**Comment by karmelyoei** [comment]
6.  Add this line in the app server side file
```js
app.use(express.static(join(__dirname, '..', 'client', 'build'))); 
```

**Comment by karmelyoei** [comment]
7. change the port of the server-side if you dont want to run your code in the port 4000 make sure your server port is the same as the one you put in the proxy command 
```js

 app.listen(4000, () => console.log('running on port 000')); 
```

**Comment by Jood80** [comment]
> 1. Run this command in the terminal to build the react and create a file called build inside your project
> 
> ```js
> npm run build
> ```

@karmelyoei  shouldn't be  ?
>```js
> npm run build:client
>```
